# Generated by Django 5.1.5 on 2025-02-02 14:48

import imagekit.models.fields
from django.db import migrations, models

import rent_house.utils.image_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Введите заголовок", max_length=50, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, help_text="Введите текст", max_length=255, null=True, verbose_name="Текст"
                    ),
                ),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Загрузите фотографию",
                        upload_to=rent_house.utils.image_utils.upload_to,
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Установить это фото и текст первым (начальным)",
                        verbose_name="Активный (начальный текст)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero-текст",
                "verbose_name_plural": "Hero-тексты",
            },
        ),
    ]
