# Generated by Django 5.1.5 on 2025-02-02 16:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herotext",
            name="text",
            field=tinymce.models.HTMLField(blank=True, help_text="Введите текст", null=True, verbose_name="Текст"),
        ),
    ]
