# Generated by Django 5.1.5 on 2025-02-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0004_aboutsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsection",
            name="additional_title",
            field=models.CharField(
                blank=True,
                help_text="Введите дополнительный заголовок",
                max_length=50,
                null=True,
                verbose_name="Дополнительный заголовок",
            ),
        ),
    ]
