# Generated by Django 5.1.5 on 2025-02-02 20:06

import imagekit.models.fields
from django.db import migrations, models

import rent_house.utils.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0005_alter_aboutsection_additional_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок карточки", max_length=50, verbose_name="Заголовок"),
                ),
                ("description", models.TextField(help_text="Введиет описание", verbose_name="Описание")),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Загрузите фотографию",
                        upload_to=rent_house.utils.image_utils.upload_to,
                        verbose_name="Фотография",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка о нас",
                "verbose_name_plural": "Карточки о нас",
            },
        ),
    ]
