# Generated by Django 5.1.5 on 2025-02-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0007_portfoliosection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliosection",
            name="text",
        ),
    ]
