# Generated by Django 5.1.5 on 2025-02-02 21:47

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models

import rent_house.utils.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0008_remove_portfoliosection_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название альбома", max_length=100, verbose_name="Название альбома"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="slug для фильтрации в шаблоне")),
            ],
            options={
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
            },
        ),
        migrations.AlterModelOptions(
            name="portfoliosection",
            options={"verbose_name": "Раздел галерея", "verbose_name_plural": "Раздел галерея"},
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Загрузите фотографию",
                        upload_to=rent_house.utils.image_utils.album_image_path,
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rent_house.album",
                        verbose_name="Галерея",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
    ]
