# Generated by Django 5.1.5 on 2025-02-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0010_delete_aboutsection_delete_portfoliosection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcard",
            options={"verbose_name": "Карточка о нас", "verbose_name_plural": "Карточки 'Что мы предоставляем'"},
        ),
        migrations.AlterModelOptions(
            name="album",
            options={"verbose_name": "Альбомы в галерею", "verbose_name_plural": "Альбомы в галерею"},
        ),
    ]
