# Generated by Django 5.1.5 on 2025-02-06 10:11

import imagekit.models.fields
import rent_house.utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0011_alter_aboutcard_options_alter_album_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithUsCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок карточки", max_length=50, verbose_name="Заголовок"),
                ),
                ("description", models.TextField(help_text="Введиет описание", verbose_name="Описание")),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Загрузите фотографию",
                        upload_to=rent_house.utils.image_utils.upload_to,
                        verbose_name="Фотография",
                    ),
                ),
                ("link", models.URLField(help_text="Укажите ссылку", verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Карточка о нас",
                "verbose_name_plural": "Карточки 'Рядом с нами'",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Активный альбом", verbose_name="Активный (начальный альбом)"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="is_published",
            field=models.BooleanField(default=True, help_text="Опубликован", verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(
                help_text="Введите название альбома", max_length=50, verbose_name="Название альбома"
            ),
        ),
    ]
