# Generated by Django 5.1.5 on 2025-02-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0012_withuscard_album_is_active_album_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"verbose_name": "Альбом галереи", "verbose_name_plural": "Альбом галереи"},
        ),
        migrations.RemoveField(
            model_name="album",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="album",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="album",
            name="slug",
        ),
    ]
