# Generated by Django 5.1.5 on 2025-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0013_alter_album_options_remove_album_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Установить этот альбом активным", verbose_name="Активный альбом"
            ),
        ),
    ]
