# Generated by Django 5.1.5 on 2025-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0014_album_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withuscard",
            name="description",
            field=models.TextField(blank=True, help_text="Введиет описание", null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="withuscard",
            name="link",
            field=models.URLField(blank=True, help_text="Укажите ссылку", null=True, verbose_name="Ссылка"),
        ),
    ]
