# Generated by Django 5.1.5 on 2025-02-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent_house", "0015_alter_withuscard_description_alter_withuscard_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"verbose_name": "Альбом галереи", "verbose_name_plural": "Альбомы галереи"},
        ),
        migrations.RenameField(
            model_name="herotext",
            old_name="photo",
            new_name="image",
        ),
    ]
